# Модуль отслеживающий надписи на табличках
SignsListener:
  Enabled: true
  # Использовать отдельный файл для вывода данных. Файл будет расположен - /plugins/SignsListener/signs.txt
  UseDifferentFile: false
  # Запретить использовать коды форматирования (символ §)
  BlockFormatting: false
  # Уведомлять сотрудников сервера имеющих привилегию SignsListener.signs.notice
  StaffNotice: false
  # Формат вывода данных. Изменяйте, только если уверены
  OutputFormat: "[SignsListener] <player> ([<world>] <x>, <y>, <z>) <text>"
  # Плагин выводит сообщение в одну строку. Можно использова "/n" для переноса каждой строки
  Separator: " + "
  # Данное сообщение выдаётся игроку если при обработке сообщения на его табличке произошла ошибка
  # Изменения будут отменены, следовательно в лог ничего выводиться не будет
  IllegalSymbols: "&cВаша табличка содержит недопустимые символы."
  FormattingBlocked: "&cВам не разрешено использовать коды форматирования на табличке."

# Модуль отслеживающий надписи в книгах
BooksListener:
  Enabled: true
  # Использовать отдельный файл для вывода данных. Файл будет расположен - /plugins/SignsListener/books.txt
  UseDifferentFile: false
  # Запретить использовать коды форматирования (символ §)
  BlockFormatting: false
  # Уведомлять сотрудников сервера имеющих привилегию SignsListener.books.notice
  StaffNotice: false
  # Формат вывода данных. Изменяйте, только если уверены
  OutputFormat: "[BooksListener] <player> ([<world>] <x>, <y>, <z>) <title> <text>"
  # Плагин выводит сообщение в одну строку. Можно использова "/n" для переноса каждой строки
  Separator: " + "
  # Сообщение, которое выводится если книга не подписана
  WithoutTitle: "<Книга не подписана>"
  # Данное сообщение выдаётся игроку если при обработке сообщения в его книге произошла ошибка
  # Изменения будут отменены, следовательно в лог ничего выводиться не будет
  IllegalSymbols: "&cВаша книга содержит недопустимые символы."
  # Сообщение, которое выдаётся если игрок использовал коды форматирования в книге.
  FormattingBlocked: "&cВам не разрешено использовать коды форматирования в книге."

# Модуль отслеживающий имена предметов
ItemsListener:
  Enabled: true
  # Использовать отдельный файл для вывода данных. Файл будет расположен - /plugins/SignsListener/items.txt
  UseDifferentFile: false
  # Уведомлять сотрудников сервера имеющих привилегию SignsListener.items.notice
  StaffNotice: false
  # Формат вывода данных. Изменяйте, только если уверены
  OutputFormat: "[ItemsListener] <player> ([<world>] <x>, <y>, <z>) <text>"
  # Данное сообщение выдаётся игроку если при обработке имени предмета произошла ошибка
  # Изменения будут отменены, следовательно в лог ничего выводиться не будет
  IllegalSymbols: "&cИмя предмета содержит недопустимые символы."